import { P } from './roles';
import {
  LayoutDashboard, Users, Target, Building2, ActivitySquare, BookUser,
  DollarSign, Megaphone, UserCog, CalendarDays,
  ClipboardList, MessageSquare, Settings, BarChart3, Wallet, ClipboardCheck,
} from 'lucide-react';

export const NAV_ITEMS = [
  { id: 'dashboard', label: { ar: 'لوحة التحكم', en: 'Dashboard' }, icon: LayoutDashboard, path: '/dashboard', permission: P.DASHBOARD },
  { id: 'crm', label: { ar: 'إدارة العملاء', en: 'CRM' }, icon: Users, permission: P.CONTACTS_VIEW_OWN, children: [
    { id: 'opportunities', label: { ar: 'الفرص البيعية', en: 'Opportunities' }, path: '/crm/opportunities', permission: P.OPPS_VIEW_OWN },
    { id: 'lead-pool', label: { ar: 'بركة الليدز', en: 'Lead Pool' }, path: '/crm/lead-pool', permission: P.POOL_VIEW },
  ]},
  { id: 'contacts', label: { ar: 'جهات الاتصال', en: 'Contacts' }, icon: BookUser, path: '/contacts', permission: P.CONTACTS_VIEW_OWN },
  { id: 'activities', label: { ar: 'الأنشطة', en: 'Activities' }, icon: ActivitySquare, path: '/activities', permission: P.CONTACTS_VIEW_OWN },
  { id: 'real-estate', label: { ar: 'العقارات', en: 'Real Estate' }, icon: Building2, permission: P.PROJECTS_VIEW, children: [
    { id: 'projects', label: { ar: 'المشاريع', en: 'Projects' }, path: '/real-estate/projects', permission: P.PROJECTS_VIEW },
    { id: 'units', label: { ar: 'الوحدات', en: 'Units' }, path: '/real-estate/units', permission: P.UNITS_VIEW },
  ]},
  { id: 'sales', label: { ar: 'المبيعات', en: 'Sales' }, icon: DollarSign, permission: P.DEALS_VIEW_OWN, children: [
    { id: 'deals', label: { ar: 'الصفقات', en: 'Deals' }, path: '/sales/deals', permission: P.DEALS_VIEW_OWN },
    { id: 'commissions', label: { ar: 'العمولات', en: 'Commissions' }, path: '/sales/commissions', permission: P.COMM_VIEW_OWN },
    { id: 'forecast', label: { ar: 'توقعات المبيعات', en: 'Sales Forecast' }, path: '/sales/forecast', permission: P.DEALS_VIEW_OWN },
  ]},
  { id: 'operations', label: { ar: 'العمليات', en: 'Operations' }, icon: ClipboardCheck, permission: P.OPS_VIEW, children: [
    { id: 'ops-overview',    label: { ar: 'نظرة عامة',         en: 'Overview' },          path: '/operations',              permission: P.OPS_VIEW },
    { id: 'ops-deals',       label: { ar: 'معالجة الصفقات',     en: 'Deal Processing' },   path: '/operations/deals',        permission: P.OPS_MANAGE },
    { id: 'ops-payments',    label: { ar: 'المدفوعات',          en: 'Payments' },          path: '/operations/payments',     permission: P.OPS_PAYMENTS },
    { id: 'ops-handover',    label: { ar: 'التسليمات',          en: 'Handover' },          path: '/operations/handover',     permission: P.OPS_HANDOVER },
    { id: 'ops-after-sales', label: { ar: 'خدمة ما بعد البيع',  en: 'After-Sales' },       path: '/operations/after-sales',  permission: P.OPS_AFTERSALES },
  ]},
  { id: 'marketing', label: { ar: 'التسويق', en: 'Marketing' }, icon: Megaphone, permission: P.CAMPAIGNS_VIEW, children: [
    { id: 'mkt-dashboard', label: { ar: 'نظرة عامة', en: 'Dashboard' }, path: '/marketing', permission: P.CAMPAIGNS_VIEW },
    { id: 'mkt-campaigns', label: { ar: 'الحملات', en: 'Campaigns' }, path: '/marketing/campaigns', permission: P.CAMPAIGNS_VIEW },
    { id: 'mkt-channels', label: { ar: 'القنوات', en: 'Channels' }, path: '/marketing/channels', permission: P.CAMPAIGNS_VIEW },
    { id: 'mkt-funnel', label: { ar: 'القمع التسويقي', en: 'Funnel' }, path: '/marketing/funnel', permission: P.CAMPAIGNS_VIEW },
  ]},
  { id: 'performance', label: { ar: 'الأداء', en: 'Performance' }, icon: Target, permission: P.HR_VIEW_OWN, path: '/performance' },
  { id: 'hr', label: { ar: 'الموارد البشرية', en: 'HR' }, icon: UserCog, permission: P.HR_VIEW_OWN, children: [
    { id: 'employees',    label: { ar: 'الموظفين',        en: 'Employees' },    path: '/hr/employees',    permission: P.HR_VIEW_OWN },
    { id: 'policies',     label: { ar: 'محرك السياسات',   en: 'Policies' },     path: '/hr/policies',     permission: P.HR_VIEW_ALL },
    { id: 'attendance',   label: { ar: 'الحضور',          en: 'Attendance' },   path: '/hr/attendance',   permission: P.ATTEND_VIEW_OWN },
    { id: 'leave',        label: { ar: 'الإجازات',        en: 'Leave' },        path: '/hr/leave',        permission: P.LEAVE_REQUEST },
    { id: 'payroll',      label: { ar: 'الرواتب',         en: 'Payroll' },      path: '/hr/payroll',      permission: P.PAYROLL_VIEW },
    { id: 'competencies', label: { ar: 'الكفاءات',        en: 'Competencies' }, path: '/hr/competencies', permission: P.HR_VIEW_OWN },
    { id: 'recruitment',  label: { ar: 'التوظيف',         en: 'Recruitment' },  path: '/hr/recruitment',  permission: P.HR_VIEW_ALL },
    { id: 'disciplinary',   label: { ar: 'الإجراءات التأديبية', en: 'Disciplinary' },          path: '/hr/disciplinary',   permission: P.HR_VIEW_ALL },
    { id: 'training',       label: { ar: 'التدريب والتطوير',      en: 'Training & Development' }, path: '/hr/training',       permission: P.HR_VIEW_ALL },
    { id: 'self-service',   label: { ar: 'بوابة الموظف',          en: 'Self-Service' },           path: '/hr/self-service',   permission: P.HR_VIEW_OWN },
    { id: 'assets',         label: { ar: 'إدارة الأصول',          en: 'Assets' },                 path: '/hr/assets',         permission: P.HR_VIEW_ALL },
    { id: 'onboarding',     label: { ar: 'الاستقبال والمغادرة',   en: 'Onboarding' },             path: '/hr/onboarding',     permission: P.HR_VIEW_ALL },
    { id: 'expense-claims', label: { ar: 'طلبات المصروفات',      en: 'Expense Claims' },         path: '/hr/expense-claims', permission: P.HR_VIEW_OWN },
  ]},
  { id: 'finance', label: { ar: 'المالية', en: 'Finance' }, icon: Wallet, permission: P.FINANCE_VIEW, children: [
    { id: 'fin-overview', label: { ar: 'نظرة عامة', en: 'Overview' }, path: '/finance', permission: P.FINANCE_VIEW },
    { id: 'fin-coa', label: { ar: 'دليل الحسابات', en: 'Chart of Accounts' }, path: '/finance/coa', permission: P.FINANCE_VIEW },
    { id: 'fin-journal', label: { ar: 'القيود اليومية', en: 'Journal Entries' }, path: '/finance/journal', permission: P.FINANCE_VIEW },
    { id: 'fin-invoices', label: { ar: 'الفواتير', en: 'Invoices' }, path: '/finance/invoices', permission: P.FINANCE_VIEW },
    { id: 'fin-expenses', label: { ar: 'المصروفات', en: 'Expenses' }, path: '/finance/expenses', permission: P.EXPENSES_VIEW_OWN },
    { id: 'fin-reports', label: { ar: 'التقارير المالية', en: 'Reports' }, path: '/finance/reports', permission: P.FINANCE_VIEW },
    { id: 'fin-budget', label: { ar: 'الموازنة', en: 'Budget' }, path: '/finance/budget', permission: P.FINANCE_VIEW },
  ]},
  { id: 'tasks', label: { ar: 'المهام', en: 'Tasks' }, icon: ClipboardList, path: '/tasks', permission: P.TASKS_VIEW_OWN },
  { id: 'calendar', label: { ar: 'التقويم', en: 'Calendar' }, icon: CalendarDays, path: '/calendar', permission: P.CALENDAR },
  { id: 'chat', label: { ar: 'المحادثات', en: 'Chat' }, icon: MessageSquare, path: '/chat', permission: P.CHAT_USE },
  { id: 'reports', label: { ar: 'التقارير', en: 'Reports' }, icon: BarChart3, path: '/reports', permission: P.RPT_SALES },
  { id: 'settings', label: { ar: 'الإعدادات', en: 'Settings' }, icon: Settings, permission: P.SETTINGS_VIEW, children: [
    { id: 'general', label: { ar: 'إعدادات عامة', en: 'General' }, path: '/settings/general', permission: P.SETTINGS_MANAGE },
    { id: 'users-mgmt', label: { ar: 'المستخدمين', en: 'Users' }, path: '/settings/users', permission: P.USERS_MANAGE },
    { id: 'audit', label: { ar: 'سجل التدقيق', en: 'Audit Log' }, path: '/settings/audit-log', permission: P.AUDIT_VIEW },
    { id: 'backup', label: { ar: 'النسخ الاحتياطي', en: 'Backup' }, path: '/settings/backup', permission: P.SETTINGS_MANAGE },
    { id: 'system-config', label: { ar: 'إعدادات النظام', en: 'System Config' }, path: '/settings/system', permission: P.SETTINGS_MANAGE },
    { id: 'user-tracking', label: { ar: 'تتبع المستخدمين', en: 'User Tracking' }, path: '/settings/tracking', permission: P.AUDIT_VIEW },
    { id: 'triggers', label: { ar: 'المشغلات التلقائية', en: 'Triggers' }, path: '/settings/triggers', permission: P.SETTINGS_MANAGE },
    { id: 'custom-fields', label: { ar: 'حقول مخصصة', en: 'Custom Fields' }, path: '/settings/custom-fields', permission: P.SETTINGS_MANAGE },
  ]},
];
