export const ROLES = {
  ADMIN: 'admin',
  SALES_DIRECTOR: 'sales_director',
  SALES_MANAGER: 'sales_manager',
  TEAM_LEADER: 'team_leader',
  SALES_AGENT: 'sales_agent',
  MARKETING: 'marketing',
  HR: 'hr',
  FINANCE: 'finance',
};

export const ROLE_LABELS = {
  admin: { ar: 'مدير النظام', en: 'Admin' },
  sales_director: { ar: 'مدير المبيعات', en: 'Sales Director' },
  sales_manager: { ar: 'سيلز مانجر', en: 'Sales Manager' },
  team_leader: { ar: 'تيم ليدر', en: 'Team Leader' },
  sales_agent: { ar: 'سيلز', en: 'Sales Agent' },
  marketing: { ar: 'تسويق', en: 'Marketing' },
  hr: { ar: 'موارد بشرية', en: 'HR' },
  finance: { ar: 'مالية', en: 'Finance' },
};

export const P = {
  DASHBOARD: 'dashboard.view',
  CONTACTS_VIEW_OWN: 'contacts.view_own',
  OPPS_VIEW_OWN: 'opps.view_own',
  POOL_VIEW: 'pool.view',
  DEVS_VIEW: 'devs.view',
  PROJECTS_VIEW: 'projects.view',
  UNITS_VIEW: 'units.view',
  DEALS_VIEW_OWN: 'deals.view_own',
  COMM_VIEW_OWN: 'comm.view_own',
  RPT_SALES: 'rpt.sales',
  CAMPAIGNS_VIEW: 'campaigns.view',
  HR_VIEW_OWN: 'hr.view_own',
  HR_VIEW_ALL: 'hr.view_all',
  ATTEND_VIEW_OWN: 'attend.view_own',
  LEAVE_REQUEST: 'leave.request',
  PAYROLL_VIEW: 'payroll.view',
  FINANCE_VIEW: 'finance.view',
  EXPENSES_VIEW_OWN: 'expenses.view_own',
  TASKS_VIEW_OWN: 'tasks.view_own',
  CALENDAR: 'calendar.view',
  CHAT_USE: 'chat.use',
  SETTINGS_VIEW: 'settings.view',
  SETTINGS_MANAGE: 'settings.manage',
  USERS_MANAGE: 'users.manage',
  ROLES_MANAGE: 'roles.manage',
  SLA_MANAGE: 'sla.manage',
  SCORING_MANAGE: 'scoring.manage',
  AUDIT_VIEW: 'audit.view',
};

export const ROLE_PERMISSIONS = {
  admin: Object.values(P),
  sales_director: [P.DASHBOARD, P.CONTACTS_VIEW_OWN, P.OPPS_VIEW_OWN, P.DEALS_VIEW_OWN, P.COMM_VIEW_OWN, P.PROJECTS_VIEW, P.UNITS_VIEW, P.RPT_SALES, P.TASKS_VIEW_OWN, P.CALENDAR, P.CHAT_USE],
  sales_manager: [P.DASHBOARD, P.CONTACTS_VIEW_OWN, P.OPPS_VIEW_OWN, P.DEALS_VIEW_OWN, P.PROJECTS_VIEW, P.UNITS_VIEW, P.RPT_SALES, P.TASKS_VIEW_OWN, P.CALENDAR, P.CHAT_USE],
  team_leader: [P.DASHBOARD, P.CONTACTS_VIEW_OWN, P.OPPS_VIEW_OWN, P.DEALS_VIEW_OWN, P.PROJECTS_VIEW, P.UNITS_VIEW, P.POOL_VIEW, P.TASKS_VIEW_OWN, P.CALENDAR, P.CHAT_USE],
  sales_agent: [P.DASHBOARD, P.CONTACTS_VIEW_OWN, P.OPPS_VIEW_OWN, P.DEALS_VIEW_OWN, P.PROJECTS_VIEW, P.UNITS_VIEW, P.POOL_VIEW, P.TASKS_VIEW_OWN, P.CALENDAR, P.CHAT_USE],
  marketing: [P.DASHBOARD, P.CAMPAIGNS_VIEW, P.CONTACTS_VIEW_OWN, P.TASKS_VIEW_OWN, P.CALENDAR, P.CHAT_USE],
  hr: [P.DASHBOARD, P.HR_VIEW_ALL, P.ATTEND_VIEW_OWN, P.LEAVE_REQUEST, P.PAYROLL_VIEW, P.TASKS_VIEW_OWN, P.CALENDAR, P.CHAT_USE],
  finance: [P.DASHBOARD, P.FINANCE_VIEW, P.EXPENSES_VIEW_OWN, P.DEALS_VIEW_OWN, P.COMM_VIEW_OWN, P.TASKS_VIEW_OWN, P.CALENDAR, P.CHAT_USE],
};
